export const AutobiographyofaYogi = [
  {
    id: 1,
    text: "The yogi must not become overly concerned if his progress does not correspond with his expectations or preconceived image, for he is dealing with a subtle science that is beyond the understanding of the unenlightened mind.",
    resource: "Autobiography of a Yogi",
    resource_page: 493,
  },
  {
    id: 2,
    text: "Giving is the secret of abundance.",
    resource: "Autobiography of a Yogi",
    resource_page: 3,
  },
  {
    id: 3,
    text: "When you find the joy of meditation, you will have simply opened the door to the kingdom of heaven.",
    resource: "Autobiography of a Yogi",
    resource_page: 287,
  },
  {
    id: 4,
    text: "True renunciation is to give up the desire to be with God in only one way, that is, on our own terms.",
    resource: "Autobiography of a Yogi",
    resource_page: 324,
  },
  {
    id: 5,
    text: "The soul loves to meditate, for in contact with the Spirit lies its greatest joy.",
    resource: "Autobiography of a Yogi",
    resource_page: 22,
  },
  {
    id: 6,
    text: "Everything else can wait, but your search for God cannot wait.",
    resource: "Autobiography of a Yogi",
    resource_page: 27,
  },
  {
    id: 7,
    text: "It is the duty of every man to help those who suffer.",
    resource: "Autobiography of a Yogi",
    resource_page: 232,
  },
  {
    id: 8,
    text: "Blessedness is not the reward of virtue; blessedness is virtue itself.",
    resource: "Autobiography of a Yogi",
    resource_page: 174,
  },
  {
    id: 9,
    text: "God is not interested in storing up treasures for us in heaven, but in bringing us to heaven itself.",
    resource: "Autobiography of a Yogi",
    resource_page: 218,
  },
  {
    id: 10,
    text: "A saint is a symbol of humility.",
    resource: "Autobiography of a Yogi",
    resource_page: 73,
  },
  {
    id: 11,
    text: "The mind is like an elastic band. The more you pull, the more it stretches. Every time you feel limitations, close your eyes and say to yourself, 'I am the Infinite,' and you will see what power you have.",
    resource: "Autobiography of a Yogi",
    resource_page: 10,
  },
  {
    id: 12,
    text: "Your own will must be strong enough to sustain you when all else fails.",
    resource: "Autobiography of a Yogi",
    resource_page: 58,
  },
  {
    id: 13,
    text: "The body is a treacherous friend. Give it its due; no more.",
    resource: "Autobiography of a Yogi",
    resource_page: 57,
  },
  {
    id: 14,
    text: "Remember that the best relationship is one in which your love for each other exceeds your need for each other.",
    resource: "Autobiography of a Yogi",
    resource_page: 440,
  },
  {
    id: 15,
    text: "The wise man teaches by his example.",
    resource: "Autobiography of a Yogi",
    resource_page: 75,
  },
  {
    id: 16,
    text: "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.",
    resource: "Autobiography of a Yogi",
    resource_page: 20,
  },
  {
    id: 17,
    text: "Life is a pilgrimage, a journey that takes us from confusion to clarity, from ignorance to understanding.",
    resource: "Autobiography of a Yogi",
    resource_page: 287,
  },
  {
    id: 18,
    text: "In this world you are identified by your acts and your desires. You are the sum total of what you think, what you want, and what you do.",
    resource: "Autobiography of a Yogi",
    resource_page: 47,
  },
  {
    id: 19,
    text: "A mind that is fast is sick. A mind that is slow is sound. A mind that is still is divine.",
    resource: "Autobiography of a Yogi",
    resource_page: 372,
  },
  {
    id: 20,
    text: "The greatest guru is your own inner self. Truly, he who can contact his inner self is indeed blessed!",
    resource: "Autobiography of a Yogi",
    resource_page: 462,
  },
  {
    id: 21,
    text: "An ounce of practice is worth more than tons of preaching.",
    resource: "Autobiography of a Yogi",
    resource_page: 546,
  },
  {
    id: 22,
    text: "Silence is the altar of spirit.",
    resource: "Autobiography of a Yogi",
    resource_page: 283,
  },
  {
    id: 23,
    text: "The soul has been sleeping in the darkness of ignorance. It is time to wake up and see the glorious light within you.",
    resource: "Autobiography of a Yogi",
    resource_page: 28,
  },
  {
    id: 24,
    text: "The path to freedom is through self-discipline.",
    resource: "Autobiography of a Yogi",
    resource_page: 4,
  },
  {
    id: 25,
    text: "The spiritually awakening person realizes that success is not measured by material wealth, but by the degree of inner peace they have attained.",
    resource: "Autobiography of a Yogi",
    resource_page: 165,
  },
  {
    id: 26,
    text: "Those who think themselves divinely endowed, and who behave as if they are already saints, have only fooled themselves.",
    resource: "Autobiography of a Yogi",
    resource_page: 482,
  },
  {
    id: 27,
    text: "We cannot seek God as something we do not already have. We must first realize that He is within us and know that His presence is the source of all joy.",
    resource: "Autobiography of a Yogi",
    resource_page: 30,
  },
  {
    id: 28,
    text: "You must love God with all your heart, without any selfish motive. That is the only way to find Him.",
    resource: "Autobiography of a Yogi",
    resource_page: 33,
  },
  {
    id: 29,
    text: "You have been blessed with a human birth; use it to realize God.",
    resource: "Autobiography of a Yogi",
    resource_page: 79,
  },
  {
    id: 30,
    text: "The soul is ever free, ever pure, ever perfect. It is only our ignorance that makes us think we are bound, impure, and imperfect.",
    resource: "Autobiography of a Yogi",
    resource_page: 146,
  },
];

export const MansEternalQuest = [
  {
    id: 1,
    text: "The greatest romance you can experience is the romance with God. Awaken that romance and your life will be filled with constant joy and happiness.",
    resource: "Man's Eternal Quest",
    resource_page: 2,
  },
  {
    id: 2,
    text: "God is ever-new joy. Every moment is a new delight when we are in tune with Him.",
    resource: "Man's Eternal Quest",
    resource_page: 18,
  },
  {
    id: 3,
    text: "Through meditation, you can calm the restlessness of the mind, and experience the eternal joy of the soul.",
    resource: "Man's Eternal Quest",
    resource_page: 129,
  },
  {
    id: 4,
    text: "Only by purifying your thoughts and actions can you attract the presence of God.",
    resource: "Man's Eternal Quest",
    resource_page: 21,
  },
  {
    id: 5,
    text: "True progress is achieved not by pushing forward, but by going inward.",
    resource: "Man's Eternal Quest",
    resource_page: 66,
  },
  {
    id: 6,
    text: "To experience the beauty of the divine, you must first experience the beauty within yourself.",
    resource: "Man's Eternal Quest",
    resource_page: 136,
  },
  {
    id: 7,
    text: "The ultimate goal of human life is to attain the oneness with God that is our true nature.",
    resource: "Man's Eternal Quest",
    resource_page: 1,
  },
  {
    id: 8,
    text: "God is the source of all beauty, love, and joy. Make Him the center of your life and you will experience those qualities in abundance.",
    resource: "Man's Eternal Quest",
    resource_page: 138,
  },
  {
    id: 9,
    text: "The purpose of life is to remember our divine origin and to live our lives in such a way that our thoughts and actions reflect that remembrance.",
    resource: "Man's Eternal Quest",
    resource_page: 17,
  },
  {
    id: 10,
    text: "True education is not the learning of facts, but the training of the mind to think, feel, and act rightly.",
    resource: "Man's Eternal Quest",
    resource_page: 49,
  },
  {
    id: 11,
    text: "God's love is the most powerful force in the universe. When we open our hearts to Him, we become channels for that love to flow to others.",
    resource: "Man's Eternal Quest",
    resource_page: 115,
  },
  {
    id: 12,
    text: "The best way to help others is to first help ourselves. By attaining inner peace and joy, we radiate those qualities to others.",
    resource: "Man's Eternal Quest",
    resource_page: 122,
  },
  {
    id: 13,
    text: "By constantly thinking of God, you can attract His blessings into your life and achieve spiritual progress.",
    resource: "Man's Eternal Quest",
    resource_page: 58,
  },
  {
    id: 14,
    text: "The spiritual path is not about finding yourself, it's about losing yourself in God.",
    resource: "Man's Eternal Quest",
    resource_page: 10,
  },
  {
    id: 15,
    text: "God is not only found in the depths of meditation, but also in the simple joys of daily life.",
    resource: "Man's Eternal Quest",
    resource_page: 12,
  },
  {
    id: 16,
    text: "When you do the right thing, you don't have to worry about the consequences; God will take care of everything.",
    resource: "Man's Eternal Quest",
    resource_page: 81,
  },
  {
    id: 17,
    text: "The greatest saints are those who are humble and recognize their own unworthiness in the face of the divine.",
    resource: "Man's Eternal Quest",
    resource_page: 23,
  },
  {
    id: 18,
    text: "Your thoughts create your reality. If you want to change your life, change your thoughts.",
    resource: "Man's Eternal Quest",
    resource_page: 134,
  },
  {
    id: 19,
    text: "To be in the world but not of the world is a great spiritual challenge, but it is possible through the practice of meditation and constant remembrance of God.",
    resource: "Man's Eternal Quest",
    resource_page: 106,
  },
  {
    id: 20,
    text: "The path to God is not always easy or comfortable, but it is always rewarding and filled with blessings.",
    resource: "Man's Eternal Quest",
    resource_page: 64,
  },
  {
    id: 21,
    text: "When you feel discouraged or alone, remember that God is always with you, guiding and protecting you every step of the way.",
    resource: "Man's Eternal Quest",
    resource_page: 79,
  },
  {
    id: 22,
    text: "God's love is unconditional and infinite. When we experience that love, all our fears and doubts vanish.",
    resource: "Man's Eternal Quest",
    resource_page: 102,
  },
  {
    id: 23,
    text: "The most important relationship you can have is with God. When you have that relationship, all other relationships fall into place.",
    resource: "Man's Eternal Quest",
    resource_page: 87,
  },
  {
    id: 24,
    text: "Meditation is the key to unlocking the door to the spiritual realm. Through meditation, you can experience the presence of God within yourself.",
    resource: "Man's Eternal Quest",
    resource_page: 109,
  },
  {
    id: 25,
    text: "The purpose of life is not to accumulate wealth, but to attain spiritual realization and union with God.",
    resource: "Man's Eternal Quest",
    resource_page: 85,
  },
  {
    id: 26,
    text: "God is the source of all strength and power. When we align ourselves with Him, we become instruments of that power.",
    resource: "Man's Eternal Quest",
    resource_page: 116,
  },
  {
    id: 27,
    text: "It is not enough to read spiritual texts or attend lectures. To truly progress on the spiritual path, you must make a sincere and sustained effort to live according to the teachings.",
    resource: "Man's Eternal Quest",
    resource_page: 9,
  },
  {
    id: 28,
    text: "The ultimate purpose of all spiritual practices is to unite the individual soul with the infinite Spirit.",
    resource: "Man's Eternal Quest",
    resource_page: 60,
  },
  {
    id: 29,
    text: "Suffering is the result of our own actions and desires. To end suffering, we must transcend those actions and desires and attain a state of inner peace.",
    resource: "Man's Eternal Quest",
    resource_page: 144,
  },
  {
    id: 30,
    text: "By realizing and experiencing the divine presence within yourself, you can recognize that same presence in all beings.",
    resource: "Man's Eternal Quest",
    resource_page: 147,
  },
];
