export const theCollectedWorks = [
  {
    id: 1,
    text: "All that one gives to others one gives to oneself. If this truth is understood who will not give to others?",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "369",
  },
  {
    id: 2,
    text: "As long as there is a sense of individuality, one is subject to grief. When one realizes oneself as the Self, the ego and the sense of grief will not arise.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "94",
  },
  {
    id: 3,
    text: "The world is illusory; Brahman alone is real. Brahman is the world. The world is not different from Brahman.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "98",
  },
  {
    id: 4,
    text: "If you make your outlook harmonious, then this world will also appear to be harmonious.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "369",
  },
  {
    id: 5,
    text: "Silence is the most potent form of work.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "206",
  },
  {
    id: 6,
    text: "One should inquire into the nature of one's own Self. This is the greatest service one can render to the world.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "85",
  },
  {
    id: 7,
    text: "One should not give up the work that has been begun. The mind should not be allowed to wander away from the work in hand.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "286",
  },
  {
    id: 8,
    text: "There is no limit to the power of the Self. It can accomplish anything.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "174",
  },
  {
    id: 9,
    text: "The world is a changing phenomenon, but the substratum of it is the unchanging reality. That alone is true.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "130",
  },
  {
    id: 10,
    text: "The 'I' thought is the ego. It is a mental delusion. It must go for the Self to shine forth in its purity.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "187",
  },
  {
    id: 11,
    text: "The mind is only a bundle of thoughts. The thoughts have their root in the I-thought. Whoever investigates the True 'I' enjoys the stillness of bliss.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "77",
  },
  {
    id: 12,
    text: "The world is not a creation of the mind; the mind itself is a projection of the world.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "125",
  },

  {
    id: 13,
    text: "The mind is by nature restless. Begin liberating it from its restlessness; give it peace; make it free from distractions; train it to look inward; make this a habit. This is done by ignoring the external world and removing the obstacles to peace of mind.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "163",
  },
  {
    id: 14,
    text: "Silence is unparalleled eloquence, the state of grace that comes from the interior.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "244",
  },
  {
    id: 15,
    text: "The Self is always shining forth pure. It is like the sun which is always shining forth light.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "299",
  },
  {
    id: 16,
    text: "The mind turned inwards is the Self; turned outwards, it becomes the ego and all the world.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "328",
  },
  {
    id: 17,
    text: "The only way to peace is to transcend the mind. Unless you transcend the mind, you are always going to be in agony.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "334",
  },
  {
    id: 18,
    text: "The 'I' in the body, the ego, is the source of all trouble.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "344",
  },
  {
    id: 19,
    text: "The great sages have all declared in unison that the ultimate purpose of human life is to attain liberation.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "356",
  },
  {
    id: 20,
    text: "The pure mind is itself Brahman; it therefore follows that the impure mind is ignorance.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "413",
  },
  {
    id: 21,
    text: "Do not worry yourself over your obsessions. Just turn your attention away from them to that which observes the coming and going of the ego and the ego's ideas.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "457",
  },
  {
    id: 22,
    text: "There is no greater mystery than this, that we keep seeking reality though in fact we are reality. We think that there is something hiding reality and that this must be destroyed before reality is gained. How ridiculous! A day will dawn when you will laugh at all your past efforts. That which will be regarded as important will be so simple and natural that relief will be spontaneous and complete.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "461",
  },
  {
    id: 23,
    text: "If the enquiry is made, the mind is forced to turn back to its source and the Self is realized. The mind will then take the form of the Self and will remain in that form alone.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "175",
  },
  {
    id: 24,
    text: "It is essential that a man should know himself. One should meditate on oneself, and attain Self-realization. God dwells within us, and His temple is the heart. Self-realization is the awareness of this within oneself.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "175",
  },
  {
    id: 25,
    text: "The individual is but a bubble on the surface of the ocean of life. He comes out of it and disappears into it.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "177",
  },
  {
    id: 26,
    text: "By constantly keeping one's attention fixed on the question 'Who am I?', one ultimately realizes one's true nature. One comes to know that one is the Self, the eternal and infinite consciousness.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "181",
  },
  {
    id: 27,
    text: "The true nature of the Self is peace, happiness and bliss. It is not something to be attained, for it is already our own nature. It is simply a matter of realizing this truth.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "186",
  },
  {
    id: 28,
    text: "When the mind is completely absorbed in the Self, it becomes pure consciousness and experiences infinite peace and happiness.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "194",
  },
  {
    id: 29,
    text: "The mind is only a bundle of thoughts. The Self is beyond the mind, and can be realized only by direct experience.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "197",
  },
  {
    id: 30,
    text: "The true nature of the Self is beyond description or definition. It can only be realized through direct experience.",
    resource: "The Collected Works of Ramana Maharshi",
    resource_page: "198",
  },
];

export const talkWithSriRamanaMaharshi = [
  {
    id: 1,
    text: "Your duty is to be and not to be this or that. ‘I am that I am’ sums up the whole truth; the method is summed up in the words ‘Be still’.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "53",
  },
  {
    id: 2,
    text: "The Self is always there and you are It. All that is required of you is to be still.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "67",
  },
  {
    id: 3,
    text: "The best way to solve the problem is to keep quiet. Do not argue with others, for it leads to resentment and disharmony.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "112",
  },
  {
    id: 4,
    text: "Silence is the true teaching. It is the perfect state. No words uttered by a guru can ever express the truth.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "150",
  },
  {
    id: 5,
    text: "What is the good of knowing the Truth if you do not practise it?",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "153",
  },
  {
    id: 6,
    text: "You are already Brahman, so why do you identify yourself with the body? The body was not there before it was born, will not be there after death, and is nonexistent in sleep.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "165",
  },
  {
    id: 7,
    text: "The mind will merge only by means of the enquiry ‘Who am I?’ The thought ‘Who am I?’ will destroy all other thoughts and eventually kill itself, like the stick used to stir the funeral pyre.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "187",
  },
  {
    id: 8,
    text: "The inquiry ‘Who am I?’ is the only method of putting an end to all misery and ushering in supreme bliss.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "196",
  },
  {
    id: 9,
    text: "When the mind becomes still, the Self will be realised.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "214",
  },
  {
    id: 10,
    text: "All that is required to realise the Self is to be still.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "218",
  },
  {
    id: 11,
    text: "The mind is like a sheet of paper with writing on it; the Self is like the paper itself. Just as the paper is always there, irrespective of the writing on it, so too the Self is always there, irrespective of the state of the mind.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "242",
  },
  {
    id: 12,
    text: "The Self is always there and it is because of its light that you know that you exist.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "183",
  },
  {
    id: 13,
    text: "The ultimate truth is so simple. It is nothing more than being in the pristine state. This is all that need be said. It is not a matter for great scholarship. It is only seeing what is.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "239",
  },
  {
    id: 14,
    text: "Doubts arise and the mind is agitated. But instead of giving in to them, you must turn within and find out the truth about yourself.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "250",
  },
  {
    id: 15,
    text: "If one realizes the truth of the Self, there is nothing else to know.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "263",
  },
  {
    id: 16,
    text: "One can realize the Self only when the ego has been eliminated. This is the goal of all spiritual practices.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "300",
  },
  {
    id: 17,
    text: "All spiritual practice consists in silencing the mind and merging it into the Self. There is no need for elaborate rituals or complicated techniques.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "337",
  },
  {
    id: 18,
    text: "The Self is always present within you. You do not have to go anywhere to find it. Just turn your attention inward and you will discover it.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "385",
  },
  {
    id: 19,
    text: "The only thing necessary for spiritual progress is the sincere desire to know the truth. This is enough to guide you on the path.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "425",
  },
  {
    id: 20,
    text: "You are the Self. You are already perfect. All you have to do is realize this truth and abide in it.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "471",
  },
  {
    id: 21,
    text: "The true nature of the Self is not something that can be grasped or attained by the mind. It is something that is always present and can only be realized by letting go of all thoughts and concepts.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "264",
  },
  {
    id: 22,
    text: "There is no greater power than the power of Self-realization. It is the power that can set you free from all bondage and suffering.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "202",
  },
  {
    id: 23,
    text: "The only way to realize the Self is to turn inward and abide in the pure consciousness that is always present within you.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "140",
  },
  {
    id: 24,
    text: "The ego is like a ghost that appears to be real but is actually only a product of our own imagination. When we investigate the nature of the ego, we realize that it has no real substance and is just a bundle of thoughts and feelings.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "113",
  },
  {
    id: 25,
    text: "The mind is a great deceiver. It makes us believe that we are separate individuals with our own personal identities, when in reality we are all manifestations of the same universal consciousness.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "19",
  },
  {
    id: 26,
    text: "The ultimate goal of all spiritual practice is to realize the Self, which is the source of all existence and the substratum of all consciousness.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "121",
  },
  {
    id: 27,
    text: "The mind is like a mirror that reflects whatever is placed before it. If we place the world before the mind, it reflects the world. If we place the Self before the mind, it reflects the Self.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "233",
  },
  {
    id: 28,
    text: "The only true spiritual practice is to turn inward and inquire into the nature of the Self. All other practices are just preparations for this ultimate inquiry.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "198",
  },
  {
    id: 29,
    text: "The Self is always present within us, shining in its own splendor. It is only because of the veil of ignorance that we fail to see it.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "222",
  },
  {
    id: 30,
    text: "The ultimate truth cannot be expressed in words or concepts. It can only be realized through direct experience.",
    resource: "Talks with Sri Ramana Maharshi",
    resource_page: "273",
  },
];
