export const theDhammapada = [
  {
    id: 1,
    text: "All that we are is the result of what we have thought.",
    resource: "The Dhammapada",
    resource_page: 1,
  },
  {
    id: 2,
    text: "Happiness comes when your work and words are of benefit to yourself and others.",
    resource: "The Dhammapada",
    resource_page: 13,
  },
  {
    id: 3,
    text: "If you light a lamp for somebody, it will also brighten your path.",
    resource: "The Dhammapada",
    resource_page: 18,
  },
  {
    id: 4,
    text: "Hatred does not cease by hatred, but only by love; this is the eternal rule.",
    resource: "The Dhammapada",
    resource_page: 24,
  },
  {
    id: 5,
    text: "The only real failure in life is not to be true to the best one knows.",
    resource: "The Dhammapada",
    resource_page: 31,
  },
  {
    id: 6,
    text: "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.",
    resource: "The Dhammapada",
    resource_page: 34,
  },
  {
    id: 7,
    text: "Let us live joyfully, not hating those who hate us. Among those who hate us, we live free of hate.",
    resource: "The Dhammapada",
    resource_page: 45,
  },
  {
    id: 8,
    text: "A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise.",
    resource: "The Dhammapada",
    resource_page: 54,
  },
  {
    id: 9,
    text: "Better than a thousand hollow words is one word that brings peace.",
    resource: "The Dhammapada",
    resource_page: 59,
  },
  {
    id: 10,
    text: "Everything that has a beginning has an ending. Make your peace with that and all will be well.",
    resource: "The Dhammapada",
    resource_page: 64,
  },
  {
    id: 11,
    text: "The root of suffering is attachment.",
    resource: "The Dhammapada",
    resource_page: 68,
  },
  {
    id: 12,
    text: "A jug fills drop by drop.",
    resource: "The Dhammapada",
    resource_page: 78,
  },
  {
    id: 13,
    text: "Speak only endearing speech, speech that is welcomed. Speech, when it brings no evil to others, is a pleasant thing.",
    resource: "The Dhammapada",
    resource_page: 81,
  },
  {
    id: 14,
    text: "Radiate boundless love towards the entire world.",
    resource: "The Dhammapada",
    resource_page: 85,
  },
  {
    id: 15,
    text: "The secret of health for both mind and body is not to mourn for the past, not to worry about the future, or not to anticipate troubles, but to live in the present moment wisely and earnestly.",
    resource: "The Dhammapada",
    resource_page: 89,
  },
  {
    id: 16,
    text: "With our thoughts, we make the world.",
    resource: "The Dhammapada",
    resource_page: 96,
  },
  {
    id: 17,
    text: "The thought manifests as the word. The word manifests as the deed. The deed develops into habit. And the habit hardens into character. So watch the thought and its ways with care. And let it spring from love, born out of concern for all beings.",
    resource: "The Dhammapada",
    resource_page: 101,
  },
  {
    id: 18,
    text: "To enjoy good health, to bring true happiness to one’s family, to bring peace to all, one must first discipline and control one’s own mind. If a man can control his mind he can find the way to Enlightenment, and all wisdom and virtue will naturally come to him.",
    resource: "The Dhammapada",
    resource_page: 111,
  },
  {
    id: 19,
    text: "Peace comes from within. Do not seek it without.",
    resource: "The Dhammapada",
    resource_page: 121,
  },
  {
    id: 20,
    text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    resource: "The Dhammapada",
    resource_page: 137,
  },
  {
    id: 21,
    text: "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.",
    resource: "The Dhammapada",
    resource_page: 145,
  },
  {
    id: 22,
    text: "In the sky, there is no distinction of east and west; people create distinctions out of their own minds and then believe them to be true.",
    resource: "The Dhammapada",
    resource_page: 174,
  },
  {
    id: 23,
    text: "Sabbe dhamma nalam abhinivesaya’ (Nothing whatsoever should be clung to).",
    resource: "The Dhammapada",
    resource_page: 200,
  },
  {
    id: 24,
    text: "A mind unruffled by the vagaries of fortune, from sorrow freed, from defilements cleansed, from fear liberated — this is the greatest blessing.",
    resource: "The Dhammapada",
    resource_page: 231,
  },
  {
    id: 25,
    text: "An insincere and evil friend is more to be feared than a wild beast; a wild beast may wound your body, but an evil friend will wound your mind.",
    resource: "The Dhammapada",
    resource_page: 242,
  },
  {
    id: 26,
    text: "To understand everything is to forgive everything.",
    resource: "The Dhammapada",
    resource_page: 271,
  },
  {
    id: 27,
    text: "Silence the angry man with love. Silence the ill-natured man with kindness. Silence the miser with generosity. Silence the liar with truth.",
    resource: "The Dhammapada",
    resource_page: 278,
  },
  {
    id: 28,
    text: "He who envies others does not obtain peace of mind.",
    resource: "The Dhammapada",
    resource_page: 301,
  },
  {
    id: 29,
    text: "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.",
    resource: "The Dhammapada",
    resource_page: 332,
  },
  {
    id: 30,
    text: "The wise ones fashioned speech with their thought, sifting it as grain is sifted through a sieve.",
    resource: "The Dhammapada",
    resource_page: 367,
  },
];

export const theHeartOfTeaching = [
  {
    id: 1,
    text: "When we come into contact with the other person, our thoughts and actions should express our mind of compassion, even if that person says and does things that are not easy to accept. We practice in this way until we see clearly that our love is not contingent upon the other person being lovable.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 11,
  },
  {
    id: 2,
    text: 'The Buddha said, "My teaching is not a dogma or a doctrine, but no doubt some people will take it as such."',
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 18,
  },
  {
    id: 3,
    text: "When conditions are sufficient, the thing will manifest itself. When conditions are no longer sufficient, it will cease to manifest. It will not go anywhere else.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 31,
  },
  {
    id: 4,
    text: "To be beautiful means to be yourself. You do not need to be accepted by others. You need to accept yourself.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 39,
  },
  {
    id: 5,
    text: "The basic teaching of Buddhism is to avoid doing harm, to cultivate good, and to purify one’s mind. These are the fundamentals of Buddhist thought, speech, and action.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 54,
  },
  {
    id: 6,
    text: "If in our daily life we can smile, if we can be peaceful and happy, not only we, but everyone will profit from it. This is the most basic kind of peace work.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 72,
  },
  {
    id: 7,
    text: "When we understand our own suffering, we can accept ourselves more easily, and from the foundation of self-acceptance, we can accept others. From the foundation of accepting others, we can embrace others more easily.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 85,
  },
  {
    id: 8,
    text: "All phenomena – birth, death, being, non-being, sameness, otherness – are in the nature of interbeing.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 99,
  },
  {
    id: 9,
    text: "Buddhism offers concrete methods to transform our suffering into happiness. It is a method of practice in order to become free.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 108,
  },
  {
    id: 10,
    text: "Enlightenment means waking up to what you truly are and then being that. Realize and be who you are. This is the end of suffering and the beginning of a little joy every day.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 123,
  },
  {
    id: 11,
    text: "By taking refuge in Buddha, we take refuge in ourselves. When we take refuge in our own capacity for understanding, we also take refuge in Buddha.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 141,
  },
  {
    id: 12,
    text: "The practice of love and compassion is based on the recognition that every person has the same wish to be happy and to avoid suffering.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 159,
  },
  {
    id: 13,
    text: "Due to his deep insight, the Buddha could see that no one is ever punished by another. No one is ever rewarded by another. One suffers or enjoys the consequences of one’s own actions.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 174,
  },
  {
    id: 14,
    text: "A Buddha is someone who has awakened and discovered that he is indivisible from the world around him, which is a continuous field of energy.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 190,
  },
  {
    id: 15,
    text: "The practice of nonviolence requires a belief in one’s own capacity for compassion and love. We need to cultivate a sense of universal responsibility towards all beings and confidence in our ability to make a difference.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 207,
  },
  {
    id: 16,
    text: "The awareness that we are always on the path is the begnning of wisdom.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 225,
  },
  {
    id: 17,
    text: "With mindfulness, we can build the capacity to recognize the negative habit energy in us and to respond in a way that will free us.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 239,
  },
  {
    id: 18,
    text: "If we are not mindful of the suffering that is going on in the world, if we are not courageous enough to listen to it, we will be overwhelmed by it.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 253,
  },
  {
    id: 19,
    text: "To understand that everything is empty is not a philosophy. It is not something you learn. It is you.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 265,
  },
  {
    id: 20,
    text: "The path of mindful living is the path of no-ill will. Ill will comes from ignorance.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 282,
  },
  {
    id: 21,
    text: "The Lotus Sutra teaches that the Buddha is not a person outside of us. Your true nature is the Buddha and the Buddha is not something outside or separate from you.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 295,
  },
  {
    id: 22,
    text: "If we are mindful, even small, daily activities can open up a sense of gratitude and wonder for the gifts of life.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 309,
  },
  {
    id: 23,
    text: "We do not have to be attached to anything in order to appreciate its presence. We need only appreciate each moment of life.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 326,
  },
  {
    id: 24,
    text: "Our true nature is the nature of no-birth and no-death. Only when we touch our true nature can we transcend the fear of non-being and death.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 341,
  },
  {
    id: 25,
    text: "The Eightfold Path is our daily practice. It is a process of training ourselves to recognize our suffering and to transform it.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 356,
  },
  {
    id: 26,
    text: "Compassion is the capacity to understand the suffering in oneself and in others, and to take action to release and heal that suffering.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 370,
  },
  {
    id: 27,
    text: "Meditation is not a means to an end. It is both the means and the end.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 387,
  },
  {
    id: 28,
    text: "The ultimate aim of the Buddha’s teachings is to develop understanding, which leads to love. When understanding arises, love comes with it.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 401,
  },
  {
    id: 29,
    text: "The Buddha taught that everything is constantly changing, and that nothing can remain the same. Life is like a river, and if you do not go forward, you will go backward.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 417,
  },
  {
    id: 30,
    text: "We have to practice looking deeply at everything in order to gain the understanding that can transform suffering into happiness.",
    resource: "The Heart of the Buddha's Teaching",
    resource_page: 432,
  },
];
